const STORAGE_KEY = 'stockflow-requirements-state';
const STATUSES = ['Draft', 'Submitted', 'Accepted by Warehouse', 'Picking in Progress', 'Partially Fulfilled', 'Fully Fulfilled', 'Ready for Delivery', 'In Transit', 'Delivered to Store', 'Stocked on Shelf', 'Out of Stock', 'Cancelled'];
const ROLE_LABELS = { employee: 'Employee', manager: 'Manager', store: 'Store', warehouse: 'Warehouse', delivery: 'Delivery', admin: 'Admin' };
const defaultInventory = [
  { description: 'Milk', upc: '000123456789', brand: 'Farm Fresh', size: '1 gal', location: 'Aisle 1', on_hand: 4, safety_stock: 6 },
  { description: 'Bread', upc: '000987654321', brand: 'Daily Bake', size: '20 oz', location: 'Aisle 2', on_hand: 12, safety_stock: 5 },
  { description: 'Eggs', upc: '000456789123', brand: 'Golden Hen', size: '12 ct', location: 'Aisle 3', on_hand: 15, safety_stock: 4 },
  { description: 'Juice', upc: '000654321987', brand: 'Orchard', size: '64 oz', location: 'Aisle 5', on_hand: 3, safety_stock: 5 },
];
const defaultUsers = [
  { name: 'maria', password: 'worker123', role: 'employee', aisle: 'Aisle 1' },
  { name: 'jamal', password: 'warehouse123', role: 'warehouse', aisle: 'Receiving' },
  { name: 'anita', password: 'manager123', role: 'manager', aisle: 'All aisles' },
];
const state = loadState();
let currentView = state.view || 'home';
let currentUser = null;
let cameraStream;
let barcodeReader;
let pendingItem;
const $ = (id) => document.getElementById(id);

function now() { return new Date().toISOString(); }
function id(prefix) { return `${prefix}-${Date.now().toString().slice(-6)}`; }
function esc(value) { return String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }
function loadState() {
  try {
    const saved = JSON.parse(localStorage.getItem(STORAGE_KEY));
    if (saved) return { ...saved, inventory: saved.inventory?.length ? saved.inventory : defaultInventory, users: saved.users?.length ? saved.users : defaultUsers, orders: saved.orders || [], alerts: saved.alerts || [], activity: saved.activity || [] };
  } catch (error) { console.warn('Saved state could not be loaded', error); }
  return { inventory: defaultInventory, users: defaultUsers, orders: [], alerts: [], activity: ['StockFlow is ready for the floor team.'], view: 'home', currentUser: defaultUsers[0] };
}
function save() { state.view = currentView; state.currentUser = currentUser; localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function notify(message) { state.activity.unshift(`${new Date().toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })} · ${message}`); state.activity = state.activity.slice(0, 30); save(); }
function addEvent(order, label) { order.timeline ||= {}; order.timeline[label] = now(); }
function setView(view) { currentView = view; document.querySelectorAll('.view').forEach((element) => element.classList.toggle('active', element.id === `${view}-view`)); document.querySelectorAll('.nav-tab').forEach((button) => button.classList.toggle('active', button.dataset.view === view)); save(); render(); }
function itemByUpc(value) { const upc = String(value || '').trim(); return state.inventory.find((item) => String(item.upc) === upc); }
function lowStock(item) { return Number(item.on_hand) <= Number(item.safety_stock); }
function statusClass(status) { return ['Fully Fulfilled', 'Ready for Delivery', 'Delivered to Store', 'Stocked on Shelf'].includes(status) ? 'success' : ['Out of Stock', 'Cancelled'].includes(status) ? 'danger' : status === 'Partially Fulfilled' ? 'warning' : ''; }

const permissions = { employee: ['home', 'scan', 'orders'], store: ['home', 'scan', 'orders'], warehouse: ['home', 'orders', 'warehouse'], delivery: ['home', 'orders', 'delivery'], manager: ['home', 'orders', 'manager'], admin: ['home', 'orders', 'manager', 'admin', 'scan', 'warehouse', 'delivery'] };
function canAccess(view) { return currentUser && permissions[currentUser.role]?.includes(view); }
function showAuthenticatedApp() { $('login-screen').hidden = Boolean(currentUser); document.querySelector('.app-shell').hidden = !currentUser; }
function render() {
  showAuthenticatedApp();
  if (!currentUser) return;
  renderHome(); renderScan(); renderOrders(); renderWarehouse(); renderDelivery(); renderManager(); renderUsers();
  $('current-user').textContent = `${currentUser.name} · ${ROLE_LABELS[currentUser.role] || currentUser.role}`;
  document.querySelectorAll('.nav-tab').forEach((button) => { button.hidden = !canAccess(button.dataset.view); });
  if (!canAccess(currentView)) setView('home');
}
function renderHome() {
  const open = state.orders.filter((order) => !['Done', 'Cancelled', 'Stocked on Shelf'].includes(order.status));
  const alerts = state.alerts.length;
  $('stat-open').textContent = open.length; $('stat-low').textContent = state.inventory.filter(lowStock).length; $('stat-out').textContent = alerts; $('stat-done').textContent = state.orders.filter((order) => ['Fully Fulfilled', 'Stocked on Shelf'].includes(order.status)).length;
  $('home-refill-count').textContent = `${state.refillList?.length || 0} items`; $('home-order-count').textContent = `${state.orders.filter((order) => order.status === 'Submitted').length} waiting`; $('home-alert-count').textContent = `${alerts} alerts`;
  $('home-queue').innerHTML = open.slice(0, 5).map((order) => `<div class="list-row"><strong>${esc(order.id)}</strong><span class="status ${statusClass(order.status)}">${esc(order.status)}</span><small>${order.items.length} items · ${new Date(order.createdAt).toLocaleString()}</small></div>`).join('') || '<p class="helper">No open orders.</p>';
  $('home-activity').innerHTML = state.activity.slice(0, 6).map((message) => `<div class="list-row"><span>${esc(message)}</span></div>`).join('') || '<p class="helper">No activity yet.</p>';
}
function renderScan() {
  const list = state.refillList || (state.refillList = []); $('draft-count').textContent = `${list.length} items`;
  $('refill-list').innerHTML = list.map((item, index) => `<div class="list-row"><div><strong>${esc(item.description)}</strong><small>UPC ${esc(item.upc)} · ${item.quantity} cases${item.location ? ` · ${esc(item.location)}` : ''}</small></div><button class="danger" data-remove-refill="${index}" type="button">Remove</button></div>`).join('') || '<p class="helper">Scan a shelf label to begin an order.</p>';
  document.querySelectorAll('[data-remove-refill]').forEach((button) => button.addEventListener('click', () => { list.splice(Number(button.dataset.removeRefill), 1); save(); render(); }));
}
function orderCard(order, includeActions = false) {
  const items = order.items.map((item) => `<li><strong>${esc(item.description)}</strong> · UPC ${esc(item.upc)} · ${esc(item.brand)} · ${esc(item.size)} · ${item.requested} requested · ${item.picked || 0} picked${item.location ? ` · ${esc(item.location)}` : ''}</li>`).join('');
  return `<article class="order-card"><div class="card-top"><div><strong>${esc(order.id)}</strong><small>${esc(order.employee)} · ${new Date(order.createdAt).toLocaleString()}</small></div><span class="status ${statusClass(order.status)}">${esc(order.status)}</span></div><ul>${items}</ul>${includeActions ? `<div class="button-row"><button class="primary" data-accept-order="${order.id}" type="button">Accept order</button></div>` : ''}</article>`;
}
function renderOrders() { const query = ($('order-search')?.value || '').toLowerCase(); $('orders-list').innerHTML = state.orders.filter((order) => JSON.stringify(order).toLowerCase().includes(query)).map((order) => orderCard(order)).join('') || '<p class="helper">No orders yet.</p>'; }
function renderWarehouse() {
  const active = state.orders.filter((order) => !['Stocked on Shelf', 'Cancelled'].includes(order.status));
  $('warehouse-orders').innerHTML = active.map((order) => `<article class="order-card"><div class="card-top"><div><strong>${esc(order.id)}</strong><small>${order.items.length} items · submitted ${new Date(order.createdAt).toLocaleString()}</small></div><span class="status ${statusClass(order.status)}">${esc(order.status)}</span></div><p class="helper">Company: North Warehouse · Pick the complete order. Zero automatically creates an out-of-stock alert.</p><div class="pick-list">${order.items.map((item, index) => `<label><span><strong>${esc(item.description)}</strong><small>UPC ${esc(item.upc)} · ${esc(item.brand)} · ${esc(item.size)} · requested ${item.requested} cases</small></span><input class="picked-input" data-order="${order.id}" data-index="${index}" type="number" min="0" value="${item.picked || 0}" /></label>`).join('')}</div><div class="button-row"><button class="primary" data-accept-order="${order.id}" type="button">Accept complete order</button>${order.status === 'Accepted by Warehouse' ? `<button data-done-order="${order.id}" type="button">Done</button>` : ''}</div></article>`).join('') || '<p class="helper">No warehouse orders waiting.</p>';
  document.querySelectorAll('.picked-input').forEach((input) => input.addEventListener('change', () => { const order = state.orders.find((entry) => entry.id === input.dataset.order); if (order) order.items[Number(input.dataset.index)].picked = Math.max(0, Number(input.value) || 0); save(); }));
  document.querySelectorAll('[data-accept-order]').forEach((button) => button.addEventListener('click', () => acceptOrder(button.dataset.acceptOrder)));
  document.querySelectorAll('[data-done-order]').forEach((button) => button.addEventListener('click', () => finishOrder(button.dataset.doneOrder)));
}
function renderDelivery() {
  const ready = state.orders.filter((order) => ['Fully Fulfilled', 'Ready for Delivery', 'In Transit', 'Delivered to Store', 'Stocked on Shelf'].includes(order.status));
  $('delivery-orders').innerHTML = ready.map((order) => `<article class="order-card"><div class="card-top"><div><strong>${esc(order.id)}</strong><small>${esc(order.store)} · ${order.items.length} items</small></div><span class="status ${statusClass(order.status)}">${esc(order.status)}</span></div><div class="button-row"><button data-delivery-action="${order.id}" data-next-status="Ready for Delivery" type="button">Ready</button><button data-delivery-action="${order.id}" data-next-status="In Transit" type="button">Left warehouse</button><button data-delivery-action="${order.id}" data-next-status="Delivered to Store" type="button">Arrived at store</button><button class="primary" data-delivery-action="${order.id}" data-next-status="Stocked on Shelf" type="button">Stocked on shelf</button></div></article>`).join('') || '<p class="helper">No orders are ready for delivery.</p>';
  document.querySelectorAll('[data-delivery-action]').forEach((button) => button.addEventListener('click', () => { const order = state.orders.find((entry) => entry.id === button.dataset.deliveryAction); if (!order) return; order.status = button.dataset.nextStatus; addEvent(order, button.dataset.nextStatus); notify(`${order.id} moved to ${button.dataset.nextStatus}`); render(); }));
}
function renderManager() {
  const query = ($('manager-search')?.value || '').toLowerCase(); const complete = state.orders.filter((order) => ['Fully Fulfilled', 'Stocked on Shelf'].includes(order.status));
  $('manager-waiting').textContent = state.orders.filter((order) => order.status === 'Submitted').length; $('manager-fulfilled').textContent = complete.length; $('manager-alerts').textContent = state.alerts.length; $('manager-pick-time').textContent = `${Math.round(state.orders.reduce((total, order) => total + ((new Date(order.timeline?.pickCompleted || now()) - new Date(order.timeline?.pickStarted || order.createdAt)) / 60000), 0) / Math.max(state.orders.length, 1))}m`;
  $('manager-inventory').innerHTML = state.inventory.filter((item) => JSON.stringify(item).toLowerCase().includes(query)).map((item) => `<div class="list-row"><div><strong>${esc(item.description)}</strong><small>UPC ${esc(item.upc)} · ${esc(item.brand)} · ${esc(item.size)}</small></div><span>${item.on_hand} on hand</span></div>`).join('') || '<p class="helper">No matching items.</p>';
  $('alerts-list').innerHTML = state.alerts.map((alert, index) => `<div class="alert-row"><strong>${esc(alert.description)}</strong><small>UPC ${esc(alert.upc)} · requested ${alert.requested} · fulfilled ${alert.fulfilled}</small><small>${esc(alert.reason)} · ${new Date(alert.createdAt).toLocaleString()}</small><button data-clear-alert="${index}" type="button">Clear</button></div>`).join('') || '<p class="helper">No active alerts.</p>';
  document.querySelectorAll('[data-clear-alert]').forEach((button) => button.addEventListener('click', () => { state.alerts.splice(Number(button.dataset.clearAlert), 1); notify('An out-of-stock alert was cleared'); render(); }));
}
function renderUsers() { $('users-list').innerHTML = state.users.map((user) => `<div class="list-row"><div><strong>${esc(user.name)}</strong><small>${ROLE_LABELS[user.role] || user.role} · Aisle ${esc(user.aisle)}</small></div><div class="button-row compact"><button data-edit-user="${esc(user.name)}" type="button">Edit</button><button class="danger" data-delete-user="${esc(user.name)}" type="button">Delete</button></div></div>`).join(''); document.querySelectorAll('[data-edit-user]').forEach((button) => button.addEventListener('click', () => editUser(button.dataset.editUser))); document.querySelectorAll('[data-delete-user]').forEach((button) => button.addEventListener('click', () => { state.users = state.users.filter((user) => user.name !== button.dataset.deleteUser); save(); render(); })); }

function showQuantity(item) { pendingItem = item; $('quantity-item-name').textContent = `${item.description} · UPC ${item.upc}`; $('quantity-input').value = 1; $('quantity-modal').hidden = false; $('quantity-input').focus(); }
function addScannedItem() { const quantity = Math.max(1, Number($('quantity-input').value) || 1); state.refillList ||= []; const existing = state.refillList.find((item) => item.upc === pendingItem.upc); if (existing) existing.quantity += quantity; else state.refillList.push({ upc: pendingItem.upc, description: pendingItem.description, quantity, location: pendingItem.location || '' }); notify(`${pendingItem.description} added to the refill list`); $('quantity-modal').hidden = true; render(); }
function handleBarcode(value) { const item = itemByUpc(value); $('scan-input').value = value; if (!item) { $('scan-status').textContent = `UPC ${value} is not in the item master.`; return; } $('item-details').innerHTML = `<strong>${esc(item.description)}</strong><span>UPC ${esc(item.upc)} · ${esc(item.brand)} · ${esc(item.size)}</span><span>${item.location ? `Location: ${esc(item.location)} · ` : ''}On hand: ${item.on_hand} · Safety: ${item.safety_stock}</span>`; showQuantity(item); }
async function openCamera() { $('camera-modal').hidden = false; $('camera-status').textContent = 'Starting camera and scanning automatically...'; try { const decoder = window.ZXingBrowser || window.ZXing; if (decoder?.BrowserMultiFormatReader) { barcodeReader = new decoder.BrowserMultiFormatReader(); barcodeReader.decodeFromVideoDevice(undefined, $('camera-video'), (result) => { if (result && !$('camera-modal').hidden) { closeCamera(); handleBarcode(result.text); } }); return; } if ('BarcodeDetector' in window && navigator.mediaDevices?.getUserMedia) { cameraStream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' } }, audio: false }); $('camera-video').srcObject = cameraStream; requestAnimationFrame(scanNativeBarcode); return; } throw new Error('No barcode decoder'); } catch (error) { console.error('Camera scanner unavailable', error); $('camera-status').textContent = 'Camera scanner unavailable. Use the typed UPC field below.'; } }
async function scanNativeBarcode() { if ($('camera-modal').hidden) return; try { const detector = new BarcodeDetector(); const codes = await detector.detect($('camera-video')); if (codes.length) { closeCamera(); handleBarcode(codes[0].rawValue); return; } } catch (error) { /* Continue polling while the camera is open. */ } requestAnimationFrame(scanNativeBarcode); }
function closeCamera() { barcodeReader?.reset(); barcodeReader = undefined; cameraStream?.getTracks().forEach((track) => track.stop()); cameraStream = undefined; $('camera-video').srcObject = null; $('camera-modal').hidden = true; }
function createOrder() { if (!state.refillList?.length) return alert('Add at least one scanned item first.'); const order = { id: id('ORD'), employee: currentUser.name, store: 'Main store', createdAt: now(), status: 'Submitted', items: state.refillList.map((item) => ({ ...item, requested: item.quantity, picked: 0, unavailable: 0 })), timeline: {} }; addEvent(order, 'requestCreated'); addEvent(order, 'submitted'); state.orders.unshift(order); state.refillList = []; notify(`${order.id} submitted by ${currentUser.name}`); render(); alert(`${order.id} sent to the warehouse.`); }
function acceptOrder(orderId) { const order = state.orders.find((entry) => entry.id === orderId); if (!order) return; order.status = 'Accepted by Warehouse'; addEvent(order, 'accepted'); addEvent(order, 'pickStarted'); notify(`${order.id} accepted by the warehouse`); render(); }
function finishOrder(orderId) { const order = state.orders.find((entry) => entry.id === orderId); if (!order) return; addEvent(order, 'pickCompleted'); const unavailable = order.items.filter((item) => Number(item.picked) === 0); order.items.forEach((item) => { item.unavailable = Math.max(0, item.requested - Number(item.picked || 0)); }); if (unavailable.length) { order.status = unavailable.length === order.items.length ? 'Out of Stock' : 'Partially Fulfilled'; unavailable.forEach((item) => state.alerts.push({ description: item.description, upc: item.upc, requested: item.requested, fulfilled: item.picked || 0, store: order.store, warehouse: 'North Warehouse', createdAt: now(), processedBy: currentUser.name, reason: 'No cases available' })); notify(`${order.id} generated ${unavailable.length} stock alert(s)`); } else { order.status = 'Ready for Delivery'; notify(`${order.id} is ready for delivery`); } save(); render(); }
function editUser(username) { const user = state.users.find((entry) => entry.name === username); if (!user) return; const name = prompt('Username', user.name); const password = prompt('Password', user.password); const role = prompt('Role: employee, manager, store, warehouse, or admin', user.role); const aisle = prompt('Aisle', user.aisle); if (name && password && aisle && ROLE_LABELS[role]) { Object.assign(user, { name: name.trim(), password, role, aisle: aisle.trim() }); save(); render(); } }
function normalizeRow(row) { const keys = Object.keys(row).reduce((all, key) => { all[key.toLowerCase().replace(/[^a-z0-9]/g, '')] = row[key]; return all; }, {}); const value = (...names) => names.map((name) => keys[name.toLowerCase().replace(/[^a-z0-9]/g, '')]).find((entry) => entry !== undefined && entry !== ''); let upc = String(value('code', 'upc', 'barcode') || '').trim(); if (/^\d+$/.test(upc) && upc.length < 12) upc = upc.padStart(12, '0'); if (!upc) return null; return { description: String(value('desc', 'description') || 'Unnamed item').trim(), upc, brand: String(value('brand') || '').trim(), size: String(value('size') || '').trim(), location: '', on_hand: 0, safety_stock: 0 }; }
function parseCsv(text) { const rows = []; let row = []; let value = ''; let quoted = false; for (let index = 0; index < text.length; index += 1) { const character = text[index]; const next = text[index + 1]; if (character === '"' && quoted && next === '"') { value += '"'; index += 1; } else if (character === '"') quoted = !quoted; else if (character === ',' && !quoted) { row.push(value); value = ''; } else if ((character === '\n' || character === '\r') && !quoted) { if (character === '\r' && next === '\n') index += 1; row.push(value); if (row.some((entry) => entry.trim())) rows.push(row); row = []; value = ''; } else value += character; } if (value || row.length) { row.push(value); rows.push(row); } const headers = rows.shift()?.map((header) => header.trim()) || []; return rows.map((values) => headers.reduce((record, header, index) => { record[header] = values[index] || ''; return record; }, {})); }
function importInventory(file) { if (!file) { $('import-status').textContent = 'Choose an Excel file first.'; return; } const extension = file.name.split('.').pop().toLowerCase(); const reader = new FileReader(); reader.onload = (event) => { try { let rows; if (extension === 'csv') { rows = parseCsv(event.target.result); } else { if (typeof XLSX === 'undefined') throw new Error('Excel parser unavailable'); const workbook = XLSX.read(event.target.result, { type: 'array', cellText: true, cellNF: false }); rows = XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]], { defval: '', raw: false }); } const items = rows.map(normalizeRow).filter(Boolean); if (!items.length) throw new Error('No rows'); state.inventory = [...state.inventory.filter((existing) => !items.some((item) => item.upc === existing.upc)), ...items]; notify(`${items.length} inventory items imported from ${file.name}`); $('import-status').textContent = `Imported ${items.length} items.`; save(); render(); } catch (error) { console.error('Inventory import failed', error); $('import-status').textContent = 'Could not read this sheet. Required columns are Code, Desc, Brand, Size.'; } }; if (extension === 'csv') reader.readAsText(file, 'UTF-8'); else reader.readAsArrayBuffer(file); }
function downloadTemplate() { const headers = ['Code', 'Desc', 'Brand', 'Size']; const example = ['000000000000', 'Example item', 'Example brand', 'Example size']; if (typeof XLSX === 'undefined') { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([`${headers.join(',')}\n${example.join(',')}\n`], { type: 'text/csv' })); link.download = 'stockflow-item-template.csv'; document.body.appendChild(link); link.click(); link.remove(); $('import-status').textContent = 'CSV template downloaded.'; return; } const sheet = XLSX.utils.aoa_to_sheet([headers, example]); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, sheet, 'Items'); XLSX.writeFile(workbook, 'stockflow-item-template.xlsx'); $('import-status').textContent = 'Excel template downloaded.'; }

document.querySelectorAll('[data-view]').forEach((element) => element.addEventListener('click', () => setView(element.dataset.view)));
$('login-form').addEventListener('submit', (event) => { event.preventDefault(); const username = $('login-username').value.trim().toLowerCase(); const password = $('login-password').value; const user = state.users.find((entry) => entry.name.toLowerCase() === username && entry.password === password); if (!user) { $('login-status').textContent = 'Username or password is incorrect.'; return; } currentUser = user; currentView = 'home'; $('login-status').textContent = ''; save(); render(); });
$('logout-btn').addEventListener('click', () => { currentUser = null; currentView = 'home'; $('login-form').reset(); render(); });
$('scan-btn').addEventListener('click', openCamera); $('manual-lookup-btn').addEventListener('click', () => handleBarcode($('scan-input').value)); $('close-camera-btn').addEventListener('click', closeCamera); $('cancel-quantity-btn').addEventListener('click', () => { $('quantity-modal').hidden = true; }); $('confirm-quantity-btn').addEventListener('click', addScannedItem); $('create-order-btn').addEventListener('click', createOrder); $('order-search').addEventListener('input', renderOrders); $('manager-search').addEventListener('input', renderManager); $('inventory-upload').addEventListener('change', (event) => importInventory(event.target.files[0])); $('import-inventory-btn').addEventListener('click', () => importInventory($('inventory-upload').files[0])); $('download-template-btn').addEventListener('click', downloadTemplate);
$('user-form').addEventListener('submit', (event) => { event.preventDefault(); const name = $('user-name').value.trim(); const password = $('user-password').value; const role = $('user-role').value; const aisle = $('user-aisle').value.trim(); if (!name || !password || !role || !aisle) return; state.users.push({ name, password, role, aisle }); event.target.reset(); notify(`${name} account added`); render(); });
render();
